### PR TITLE
Compute cluster similarities

### LINKED ISSUE #41: important bug: merged clusters not being shown to similar clusters properly
If you merge two clusters, these seem to stop appearing in the list of similar clusters for others. E.g. 

image

image

Then I merge 441 and 1336, and when I select the new cluster (1770) I correctly see:

image

But if I select 185:

image

1770 should be in the list!! With a score of 0.931 (the max of its constituent templates against 185).

### PR DESCRIPTION
**Pull request by rossant**
* Closes #41
* Closes #45

### CODE REVIEW

**Comment by rossant** [comment]
@nsteinme @nippoo can you try this one and see if it the bug? You also need the accompanying kwikteam/phy#699

**Comment by nsteinme** [comment]
I am on the road until the 20th, sorry, won't be able to check it sooner than that. But @mmyros may be another person who could test it? (see his comment on #41 )

**Comment by nippoo** [comment]
Hey @rossant - this looks great - this is very similar to what I implemented in the end.

Your implementation is about 30% faster than mine because you calculate it more simply for `cj < self.n_templates` - but it *still* takes an overhead of about 390ms to run `similarity()` *every time you click on a cluster* (for me it was 600ms, which stands to reason!) on one of Nick's datasets, using an SSD. This is probably because, even cached, `_sim_ij()` takes 0.3ms or so per cluster, and you're calling it 1000 times every time you load a cluster.

I don't think 400ms is really going to work every time you click on a cluster... maybe this will do for now (though #45 runs much faster). I think, sadly, the way to do this will probably be to memcache the whole similarity matrix and calculate it once at first load. Updating for merge and split operations by `connect`ing to an `UpdateInfo` instance will be a bit of a pain, but you'll be able to do it in milliseconds per-cluster.

**Comment by nippoo** [comment]
PS it does work fine, but takes 400ms every time you click on a cluster. The whole cluster-load operation takes about 3000ms on this dataset anyway, so 400ms isn't the majority of the time, but if we want to get it under 500ms then this operation alone eats up 80% of the latency budget ;)

**Comment by rossant** [comment]
First step is to fix the bug, then to make things faster...

**Comment by rossant** [comment]
hold on don't merge yet

**Comment by nippoo** [comment]
Yep noted!

So this looks great to merge and works correctly - thanks! Alternatively if you want to merge my PR instead, that should work and be 300ms quicker for the moment but isn't as good an algorithm (only takes the "main template"). Either way!

**Comment by rossant** [comment]
This PR might be faster with https://github.com/kwikteam/phy/pull/700 -- feel free to test

**Pull request merged**
