### PR TITLE
Probe view in the template GUI

### PR DESCRIPTION
**Pull request by rossant**

### CODE REVIEW

**Comment by yger** [comment]
The new view is working fine. However, should it really be a different view, and not integrated with the WaveformView? Why not putting, in the WaveformView, a gray dot at the position of every probe by default, and if templates/waveforms are drawn on top of them, remove them? 
Otherwise, if you keep a distinct view, then maybe add a mecanism that will more clearly show when several templates are on the same channel: currently, in the probeview, the color of the last selected template is masking all other colors, if templates are overlapping.

**Comment by rossant** [comment]
I don't think putting everything in the same view would work well on very long probes like in the cortex. I'll try to find a solution for the multiple clusters issue.

**Comment by yger** [comment]
Ok, fine for me, let's go for multiple views. Regarding the problem of the colors, don't bother, this is a detail. The proper solution would, I guess, be to draw a circle with multiple colors (like a camembert) when multiple templates are covering it. But this may be too complicated

**Comment by rossant** [comment]
I updated the PR in phy to show multiple colors per channel if there are multiple clusters, let me know if that's better.

**Comment by yger** [comment]
This is working fine. Good for me

**Pull request merged**
