### PR TITLE
Add new action to split a cluster according to the original templates

### LINKED ISSUE #61: option to un-merge clusters
It would be great if there was an option to replace a given cluster by the original clusters (that appear in spike_templates.npy). This would allow Kilosort to make putative (but not final) merges, write those into spike_clusters.npy and then allow the user to undo Kilosort's merge.

### PR DESCRIPTION
**Pull request by rossant**
Closes #61.

### CODE REVIEW

**Comment by rossant** [comment]
@nsteinme this isn't much tested, feel free to try. This PR adds a new action with `shift+ctrl+k` hotkey to split one or several clusters according to the original assigned templates (as defined in `spike_templates.npy`).

**Comment by nsteinme** [comment]
Thanks, will test!

**Comment by rossant** [comment]
@nsteinme ready to merge if you're happy with it

**Comment by nsteinme** [comment]
Hey Cyrille, I just tested this and it worked for me. However it didn't work on Marius's computer. He's about to post about it.

**Comment by marius10p** [comment]
Ok, so it seems like I have the right phy-contrib repository version, but my Phy environment is not finding the right version perhaps? CTRL+SHIFT+K does not do anything.

**Comment by nsteinme** [comment]
He seemed to successfully check out the split-templates version of
phy-contrib and got the same 11 changes to gui.py that I saw. We also did
python setup.py develop from his phy environment. Is there a way to tell
for sure whether the code is being run from the place you think it is being
run from?

On Tue, Sep 27, 2016 at 4:52 PM, Marius Pachitariu <notifications@github.com

**Comment by rossant** [comment]
In a Python console: `import phycontrib; print(phycontrib.__file__)`

**Comment by marius10p** [comment]
Ok, it seemed print(phycontrib.__file__) pointed to the miniconda Phy environment. Then I did python setup.py develop again in both phy and phycontrib, and now print(phycontrib.__file__)  pointed to the Github repository. But then when I changed drive letter (i.e. from C: to G: where the data is), and started python again, print(phycontrib.__file__) reverted to the miniconda Phy location. So I moved the data to C:, and starter phy template-gui, but I still couldn't get CTRL+SHIFT+K to work.

**Comment by rossant** [comment]
I would suggest to `pip uninstall phy phycontrib`, delete the GitHub repos completely, and checkout them again (master branch now that I've merged everything). Then, do File>About to see the version. That will tell us if the problem is that you have the wrong version, or if the shortcut doesn't work on Windows.

**Comment by marius10p** [comment]
Can you please walk me through it? pip uninstall phy does not find phy

Cannot uninstall requirement phy, not installed. 

I can activate phy though...

**Comment by marius10p** [comment]
I get an error when I do that. Last few lines:

**Comment by marius10p** [comment]
File "C:\Users\Marius\Miniconda3\envs\phy\lib\site-packages\pip\req\req_instal
l.py", line 687, in uninstall
    '(at %s)' % (link_pointer, self.name, dist.location)
AssertionError: Egg-link c:\code\github\phy does not match installed location of
 phy (at c:\users\marius\miniconda3\envs\phy\lib\site-packages)

**Comment by rossant** [comment]
something is wrong with the installation...
go manually to c:\users\marius\miniconda3\envs\phy\lib\site-packages and delete everything that contains phy in it, and then try again checking out the repos and doing `python setup.py develop`. You should not move the repos after that

**Pull request merged**
