### PR TITLE
Fix template features view

### PR DESCRIPTION
**Pull request by rossant**

### CODE REVIEW

**Comment by nsteinme** [comment]
Hey Cyrille, what did you see that made you think it might not be working properly yet? It looks ok to me though I only checked a couple of pairs.

**Comment by rossant** [comment]
image

Eijkman_20160521_M2_g0_t0.imec_AP_CAR.bin
clusters 128, 159

**Comment by nsteinme** [comment]
You are referring to the horizontal and vertical "borders" in the clouds?
Those are true features of the data, they don't indicate a problem. If
that's all, then I think this is good to go. Let me know if you meant
something different about that image.

**Comment by rossant** [comment]
Yes, that's it, I'm not sure about what these features represent, so I thought it could be a problem in the code... If that's all right, then this is good to go!

**Pull request merged**
