### PR TITLE
Load and save labels in CSV files

### LINKED ISSUE #70: Arbitrary cluster labels
@marius10p and I were talking about how it would be helpful both for the experimenter's later use and in the service of developing better quality metrics if we had the ability to assign a more specific evaluation than just "noise", "mua", or "good". I.e. keep those existing options (and retain the special meanings of 0-3), but also have the ability to assign an arbitrary number as a group label. Maybe could be most easily implemented as a snippet: ":g 67" for instance. Any number >3 would be colored green in cluster view (or could be colored on a graded scale, relative to the max number currently in the list? that'd be cute but not very important), and anything >3 would be included in future "closest match" lists, just like Good are currently. That is, treat them just like Good. 

Hope that might be easy to implement in the short term, would be great to give it a try, there is a lot of interest in developing better quality metrics right now and this would be a really useful step towards that. The idea is you could see which objective measures can best predict these sliding-scale ratings with more confidence than just predicting a binary is-it-Good-or-not, since Good may include lots of different things. Thanks!

### PR DESCRIPTION
**Pull request by rossant**
Closes #70. Requires https://github.com/kwikteam/phy/pull/714

### CODE REVIEW

**Comment by nsteinme** [comment]
Looks like this works! Very cool. Agreed with recent suggestion that it would be great if the labels in any csv file became sortable columns in ClusterView (immediately gives option to sort by good/mua/noise, and then also sort by whatever else you make).

I do have one functionality suggestion. Applying the label to all selected clusters is a good idea, but can we differentiate between those selected in ClusterView vs those selected in SimilarityView? Or if not, can we make it so that there is also a snippet for just labeling the first (blue) selected one? Here's the reason: I'm going through sorting, comparing some similar clusters to the "best". Finally I'm done looking at the "best" and I'm ready to give it a label. But I don't want to have to click it to select only that one cluster (and then have to re-enable similarity view on the next cluster), or to type out the cluster number in the snippet every time. Does it make sense? How about if ":l" labels either the ones you specify or, if none specified, it labels only the first selected one; and ":la" labels all selected. Sound reasonable?

**Comment by nsteinme** [comment]
oh p.s. rather than "cluster_blah.csv" it just created "blah.csv". I think "cluster_" is sensible for all labels, and works nicely with the existing cluster_groups.

**Comment by rossant** [comment]
@nsteinme will you ever need to apply the label to all clusters from both cluster and similarity views? Or can we just have one label snippet that applies only to clusters in the cluster view?

**Comment by rossant** [comment]
if we apply `label` to clusters from the cluster view only, the `move` snippet will also change accordingly. Doing `:move good` will move clusters from the cluster view to good, whereas currently it would also move clusters from the similarity view.

**Comment by nsteinme** [comment]
I didn't know about :move! Could you add it to
https://github.com/kwikteam/phy-contrib/blob/master/docs/template-gui.md#snippets
(along with any others)? PS I have had a lot of positive feedback about
that doc page from some of the many people I've sent it to. Could we also
put a link to it from the main page of phy and phy-contrib repositories?

Ok but back to the point, I think having only one mode which applies to
cluster view is fine for me - I can't think of a situation when you want
both cluster and similarity view ones to have the same label, and if :label
can take cluster numbers as an argument, then that would be a fine
workaround in the case you do want to label both the one from cluster view
and from similarity view. Re: :move good, it makes more sense anyway to
have this be the same behavior as Alt+G, doesn't it? I don't know, anyway
that all sounds good to me.

**Comment by rossant** [comment]
> I didn't know about :move! Could you add it to the documentation (along with any others)?

OK https://github.com/kwikteam/phy-contrib/pull/76

> Could we also
> put a link to it from the main page of phy and phy-contrib repositories?

OK https://github.com/kwikteam/phy/pull/718

**Pull request merged**
