### PR TITLE
Adds usage documentation

### PR DESCRIPTION
**Pull request by stephenlenzi**

### CODE REVIEW

**Comment by rossant** [comment]
thanks @stephenlenzi looks great!

could you remove the src directory? also maybe you could rename the file to `template-gui.md`

@nsteinme could you review this one? Thanks

**Comment by nsteinme** [comment]
Yes, looks excellent. I will give a detailed look at all the text, but in
the meantime it would be great if we could add these things:

1) A list of all snippets and a description of how to use them (Cyrille, I
went back to an old email where you had directed me how to find them, but
the links there are broken now)
2) A list of any parameters that can be set in a user_settings.py (is there
such a thing anymore?)
3) A list of the data files that are required to run it (the .npy files),
and what they contain (size of matrix and brief description). Also the two
files that are created when you save. And a link to the repository for
reading these in matlab.
4) An FAQ, e.g. "What if I open the gui but traceview and waveformview are
empty? Then the gui did not find your raw data file or could not load it.
Check that params.py points to the correct file."

Maybe 1 and 2, at least, are for Cyrille to add? I could do 3 and 4.
Cyrille can you tell me how to contribute to a PR, is that a thing that can
be done? I check out the PR, make my edits, commit them, and then what?
Push?

Thanks both!

Nick

**Comment by rossant** [comment]
I suggest we review this PR and once it's good, merge it. Then we can do subsequent PRs with more additions.

**Comment by stephenlenzi** [comment]
Okay, great. I made the changes you suggested - let me know if there are any problems. If you need me to help with anything else, let me know.

**Comment by nsteinme** [comment]
Ok, I've had a chance to review the document, here are some thoughts (Cyrille see a couple questions for you also inline): 

1) Let's separate out the stuff about Kilosort to that repository. The help file here could say something like "You must start with some automatically sorted data, e.g. by using Kilosort on your data." and provide a link to the kilosort repository. And then "hardware requirements" should just be about phy. I think it should recommend an SSD; **Cyrille** how much RAM should be rec/req'd? 

2) Correlogram view is showing: the auto-correlograms of each cluster's spike trains, in color on the diagonal; the cross-correlograms of each pair of spike trains from the selected clusters, in white off-diagonal. 

3) Waveform view does not show every event in a cluster, only a small subset of them - this is important. You won't necessarily see any rare outliers there! I would say "Noise _may_ show up as having a wide range of highlighted channels" - there are lots of different kinds of noise people might have so I wouldn't want to say something is definitely a characteristic of every kind of noise. 

4) Amplitude view - this is actually showing the scale of the template for each particular spike - this is not exactly the peak amplitude (you have this correct under "additional user protocols"), and an important point is that it will depend on the template, so the amplitude view points are not necessarily comparable across templates. 

5) Feature view - the PC features shown were _not_ what were used in the automatic sorting. They are just computed and shown to you for your own purposes. Here is how the grid is arranged and how selection works: ctrl+left click on waveform view will choose a "channel0" and ctrl+right click will choose a "channel1". Then feature grid shows:
image

So there are four features you can see (channel0 pc0 and 1, channel1 pc0 and 1) and each of these is on its own row and column to give you all vs. all, but the main diagonal is special, with time always on the x-axis. 

6) In the usage summary, please add that choosing Save will also make spike_clusters.npy, a file containing the cluster identities of each spike. We will also include this in a list of all the files and what they contain, in a next revision. 

7) In step 1, you can point out that selecting the most similar cluster is accomplished rapidly by just pressing spacebar. Selecting the next most similar (in step2) is also accomplished with the spacebar. 

8) In step3, I would point out that the auto- and cross-correlograms will not be very meaningful if the spike rates are low. In other words, if it looks noisy or there are few events per bin, then it is not telling you much one way or the other. 

9) When describing splitting, I would emphasize that you need to hold down ctrl while you click all the points that define your desired polygon. **Cyrille**, how do you clear the polygon if you want to start over? Hacky way at least is to execute the split then ctrl+z to undo.

**Comment by rossant** [comment]
> Cyrille how much RAM should be rec/req'd?

I would suggest 32G 

> 9) When describing splitting, I would emphasize that you need to hold down ctrl while you click all the points that define your desired polygon. Cyrille, how do you clear the polygon if you want to start over? Hacky way at least is to execute the split then ctrl+z to undo.

ctrl+right click

**Comment by nsteinme** [comment]
Great! Thanks very much Stephen. Cyrille, I recommend we merge this, then you can add my 1 and 2 from the top of this thread (list of snippets and user_settings or phy_config options) and I can add 3 and 4 (list of required files and their contents, FAQ). I will probably commit those changes to this document directly if that's ok with you - let me know if you'd prefer another pull request.

**Comment by nsteinme** [comment]
ok, will do -

**Comment by mmyros** [comment]
Hi all, sorry to hijack this but I found no better way to contact Stephen. I stumbled upon the documentation and got curious about a passage about bursts: 

> Clusters belonging to a burst from the same neuron have signature CCGs: the smaller of the two reliably follows the larger by a very short interval (1-3ms)

Do you have any references for this by chance, maybe from patch clamp literature or something similar? It makes sense that such a situation would arise from bursting, but these may also come from synaptically connected neurons (for instance see [Ito 2014](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0105324) ). I'm interested in hearing your thoughts. Thanks!

**Comment by nsteinme** [comment]
The classic reference here is: 
Harris KD, Henze DA, Csicsvari J, Hirase H, Buzsáki G (2000) Accuracy of tetrode spike separation as determined by simultaneous intracellular and extracellular measurements. J Neurophysiol 84:401–414.

In which they did juxtacellular recordings to obtain ground truth. See their Fig 6E for an example of the kind of CCG we mean to describe here. The main difference between this and a monosynaptic connection is that the CCG is MUCH more dramatically asymmetric in this bursting case than in a monosynaptic connection, _and_ the waveforms are similar except with an amplitude scaling. I will try to collect some examples of both of these things from my own data to add to this section. 

Of course, it's without question there is an ambiguity: you could have an _especially large_ monosynaptic connection from a first neuron to a second, otherwise low-firing-rate neuron that just happens to be the same neuron type except a bit further away from the electrode array, thus appearing smaller than the first. In this case you could be tricked into thinking it is a single neuron bursting rather than two neurons with a very large monosynaptic connection. We can infer that this situation is extremely unlikely because we never see (or, I have never seen) such a strongly asymmetric CCG between two neurons that _don't_ have the same waveform shape and/or don't occupy the same channels on the array (in that case you would have proof that it can't be a single neuron bursting), which you would expect to see if it were possible to have such a strongly asymmetric CCG from something other than bursting. So in practice I think the decision is unambiguous.

**Pull request merged**
